### ISSUE TITLE
Where is download directory, default directory is empty  

### ISSUE THREAD

**Issue by Logbio** [chenditc/safari-download#19]
Anyone could advise where I can find downloaded books on my computer?Download directory is empty, when searched for the files nothing is found. Please advise

**Comment by ultrasound** [comment]
I am not sure that I think it doesn't work anymore.
I could download a book almost 1 month ago. but I can't do that today.

**Comment by mohammedzamakhan** [comment]
Same here

**Comment by owen800q** [comment]
I have already tested on ubuntu desktop 16.04, but when download process  finished, there have no file in Download directory...

**Comment by chenditc** [comment]
I just tested the version released on [Chrome Plugin](https://chrome.google.com/webstore/detail/safari-books-download/anlpljppoinmpaedoilhjibjehpjhcob?hl=en-US&gl=US) page with the sample in README.md, it still works for me. Please try download a normal file in chrome, then check the chrome's default download location, instead of OS's download directory.
